#!/usr/bin/env python3
"""Generate 500 SKILL.md files for Innovative Lab of Optometry Agent Swarm."""
import os, textwrap

BASE = "/home/z/my-project/download/innovative-lab-of-optometry/skill"

def mk(name, cat, desc, triggers, role):
    t = ", ".join(triggers)
    return f"""# Skill: {name}

## Category
{cat}

## Description
{desc}

## Trigger Words
{t}

## Sub-Agent Role
{role}

## Parallel Capable
Yes

## Agent Swarm Priority
3

## Execution Mode
When triggered, this skill spawns a focused sub-agent that independently processes the task and returns structured output to the swarm orchestrator.
"""

S = []

# ══════════════════════════════════════════
# MASTER SKILL LIST — 500 ENTRIES
# Each tuple: (name, category, description, [triggers], role)
# ══════════════════════════════════════════

# ── 1. CLINICAL REFRACTION (1-30) ──
S.append(("manifest-refraction","Clinical Refraction","Perform comprehensive manifest refraction including sphere, cylinder, axis determination using Jackson Cross Cylinder, fogging, and binocular balancing techniques for accurate spectacle prescription.",["refraction","prescription","glasses","spectacle","manifest","subjective refraction","visual acuity"],"Primary refraction agent — performs full subjective refraction workflow."))
S.append(("retinoscopy","Clinical Refraction","Perform streak retinoscopy for objective refractive error measurement with working distance calculation, neutralization, and conversion to spectacle plane.",["retinoscopy","streak retinoscopy","objective refraction","neutralization","skiascopy"],"Objective measurement agent — provides baseline refractive data."))
S.append(("auto-refraction-analysis","Clinical Refraction","Interpret auto-refractor output from Nidek, Topcon, Zeiss. Cross-reference with subjective findings and identify when to override machine values due to cataracts or media opacities.",["auto-refractor","auto-refraction","keratometer","Nidek","Topcon","ARK"],"Data validation agent — cross-references instrument output."))
S.append(("cycloplegic-refraction","Clinical Refraction","Perform cycloplegic refraction using cyclopentolate, tropicamide, or atropine for pediatric patients, esophoria, accommodative spasm, and latent hyperopia.",["cycloplegic","cyclopentolate","atropine","tropicamide","dilated refraction","pediatric refraction"],"Specialized pharmacological refraction agent."))
S.append(("binocular-balancing","Clinical Refraction","Apply binocular balancing: alternate cover test balance, prism dissociated balance, and Humphriss immediate contrast for equal accommodative stimulus.",["binocular balance","balancing","Humphriss","prism dissociated"],"Balance verification agent — ensures symmetrical output."))
S.append(("refine-cylinder-axis","Clinical Refraction","Refine cylinder axis using Jackson Cross Cylinder at 090 and 180 positions. Handle high astigmatism above 3D and irregular corneal cases.",["cylinder axis","JCC","Jackson Cross Cylinder","astigmatism axis","refine axis"],"Axis precision agent — sub-degree axis determination."))
S.append(("refine-cylinder-power","Clinical Refraction","Refine cylinder power using JCC flipping. Determine endpoint criteria and manage patient fatigue during refinement.",["cylinder power","JCC power","refine cylinder","astigmatism power"],"Power refinement agent — optimizes cylinder magnitude."))
S.append(("plus-sphere-endpoint","Clinical Refraction","Apply maximum plus/minimum minus technique to prevent over-minusing. Identify pseudomyopia and use red-green test cross-verification.",["maximum plus","plus endpoint","over-minus","pseudomyopia","red-green test","fogging"],"Endpoint verification agent — prevents over-minus error."))
S.append(("trial-frame-refraction","Clinical Refraction","Perform refraction using loose lenses in trial frame for irregular corneas, post-surgical eyes. Handle lens stacking and vertex distance adjustments.",["trial frame","loose lenses","manual refraction","lens stacking","vertex distance"],"Manual refraction agent — handles non-automated cases."))
S.append(("near-refraction-add","Clinical Refraction","Determine near add using amplitude measurement, NRA/PRA, fused cross-cylinder, and age-based tables. Covers degressive and computer vision adds.",["near add","reading add","presbyopia","NRA","PRA","amplitude","degressive"],"Presbyopia specialist — determines optimal near addition."))
S.append(("amplitude-accommodation","Clinical Refraction","Measure amplitude using Donder push-up, minus lens method, and Hofstetter formula. Compare to age norms for premature presbyopia screening.",["amplitude","accommodation","push-up","Donder","Hofstetter","premature presbyopia"],"Accommodative assessment agent."))
S.append(("monocular-estimation-mem","Clinical Refraction","MEM retinoscopy to assess accommodative posture at near for diagnosing accommodative excess, lag, and spasm.",["MEM","monocular estimation","accommodative posture","near retinoscopy","NPA"],"Near-point posture assessment agent."))
S.append(("distance-visual-acuity","Clinical Refraction","Measure distance VA using Snellen, LogMAR, ETDRS charts. Handle projector, LCD, paper formats with proper notation.",["visual acuity","Snellen","LogMAR","ETDRS","distance vision","6/6","20/20"],"Acuity measurement agent."))
S.append(("near-visual-acuity","Clinical Refraction","Measure near VA using Jaeger, Radner, MNREAD. Record working distance, print size, reading speed for low vision and presbyopia.",["near acuity","Jaeger","reading acuity","Radner","MNREAD","near vision"],"Near acuity specialist."))
S.append(("pinhole-acuity","Clinical Refraction","Pinhole occluder to differentiate refractive from organic reduced VA. Interpret improvement thresholds.",["pinhole","pinhole acuity","organic vs refractive","media opacity"],"Quick screening agent for pathology."))
S.append(("vertex-distance-compensation","Clinical Refraction","Calculate vertex distance compensation for prescriptions above +/-4.00D. Convert spectacle to corneal plane for CL and surgery planning.",["vertex distance","vertex compensation","high Rx","power conversion","spectacle plane"],"Rx conversion agent — high-power mathematics."))
S.append(("over-refraction","Clinical Refraction","Over-refraction over existing spectacles or CL to determine residual error considering current lens power and centration.",["over-refraction","residual error","existing glasses","over CL"],"Residual error determination agent."))
S.append(("dynamic-retinoscopy","Clinical Refraction","Dynamic retinoscopy (Nott, Mohindra, Bell) for real-time accommodative response assessment in pediatric and special populations.",["dynamic retinoscopy","Nott","Mohindra","Bell","pediatric retinoscopy"],"Dynamic assessment agent."))
S.append(("refraction-special-populations","Clinical Refraction","Adapt refraction for infants, non-verbal patients, cognitive impairment, nystagmus using preferential looking and Teller acuity.",["infant refraction","non-verbal","nystagmus","cognitive impairment","preferential looking","Teller acuity"],"Special populations refraction agent."))
S.append(("spectacle-prescription-writing","Clinical Refraction","Write complete spectacle prescriptions with proper notation, prism, slab-off, segment height, and lens material recommendations.",["prescription writing","Rx format","prism notation","slab-off","segment height","lens material"],"Prescription formatting agent."))
S.append(("anisometropia-management","Clinical Refraction","Manage anisometropic patients with significant inter-ocular differences. Calculate aniseikonia and recommend lens modifications.",["anisometropia","aniseikonia","unequal Rx","image size","inter-ocular difference"],"Anisometropia specialist."))
S.append(("astigmatism-classification","Clinical Refraction","Classify astigmatism: WTR, ATR, oblique, regular vs irregular, corneal vs lenticular origin.",["astigmatism type","WTR","ATR","oblique","regular astigmatism","irregular astigmatism"],"Classification agent for astigmatism subtypes."))
S.append(("presbyopia-diagnosis","Clinical Refraction","Diagnose presbyopia through age correlation, symptom analysis, near point recession, and amplitude testing.",["presbyopia","near difficulty","age-related","reading problems","add power"],"Presbyopia diagnostic agent."))
S.append(("refractive-error-epidemiology","Clinical Refraction","Analyze prevalence of myopia, hyperopia, astigmatism across populations with genetic and environmental risk factors.",["myopia prevalence","epidemiology","refractive error statistics","population study","myopia boom"],"Epidemiology analysis agent."))
S.append(("contact-lens-over-refraction","Clinical Refraction","Over-refraction with diagnostic CL to determine final CL power accounting for lens flexure and tear lens.",["CL over-refraction","contact lens power","tear lens","lens flexure","CL Rx"],"CL power determination agent."))
S.append(("refraction-post-surgical","Clinical Refraction","Refraction after cataract, LASIK, PRK, SMILE, RK, corneal transplant. Handle irregular astigmatism and IOL power residuals.",["post-surgical refraction","post-LASIK","post-cataract","IOL power","corneal transplant","SMILE","PRK"],"Post-surgical refraction specialist."))
S.append(("spectacle-lens-design-selection","Clinical Refraction","Select lens design: single vision, bifocal, progressive, occupational, anti-fatigue based on Rx and lifestyle.",["lens design","progressive","bifocal","occupational lens","anti-fatigue","Varilux","Zeiss"],"Lens design advisor."))
S.append(("refraction-pediatric-protocol","Clinical Refraction","Standardized pediatric refraction following AAP/AAO guidelines with cycloplegic dosing and amblyopia risk assessment.",["pediatric protocol","AAP guidelines","AAO guidelines","amblyopia screening","emmetropization"],"Pediatric protocol agent."))
S.append(("low-contrast-acuity","Clinical Refraction","Measure low contrast visual acuity using CSV-1000, Pelli-Robson, and Mars charts. Essential for early disease detection and functional vision assessment.",["low contrast","CSV-1000","Pelli-Robson","Mars","contrast sensitivity","functional vision"],"Contrast sensitivity assessment agent."))
S.append(("wavefront-refraction","Clinical Refraction","Interpret wavefront aberrometry data including Zernike coefficients, higher-order aberrations, and point spread function for customized corrections.",["wavefront","aberrometry","Zernike","higher-order aberrations","point spread function","customized refraction"],"Wavefront analysis agent."))

# ── 2. CONTACT LENS (31-65) ──
S.append(("soft-contact-lens-fitting","Contact Lens","Fit soft CL including base curve selection, diameter, material choice (hydrogel vs SiHy), and fluorescein parameter verification.",["soft CL","contact lens fitting","base curve","silicone hydrogel","hydrogel","Acuvue","Dailies"],"Soft CL fitting agent."))
S.append(("toric-contact-lens-fitting","Contact Lens","Fit soft toric CL for astigmatic correction with stabilization assessment, axis alignment, and rotation compensation.",["toric CL","astigmatism CL","toric lens","lens rotation","axis alignment","stabilization"],"Toric CL specialist."))
S.append(("rigid-gas-permeable-fitting","Contact Lens","Fit RGP CL with diagnostic lens selection, fluorescein pattern interpretation, peripheral curve design, and parameter ordering.",["RGP","rigid gas permeable","fluorescein pattern","alignment","steep fit","flat fit"],"RGP fitting agent."))
S.append(("keratoconus-cl-fitting","Contact Lens","Specialized CL fitting for keratoconus: Rose K, Scleral, hybrid, piggyback. Correlate with topography and grade cone severity.",["keratoconus","Rose K","scleral lens","keratoconus CL","cone fitting","hybrid CL"],"Keratoconus CL specialist."))
S.append(("scleral-lens-fitting","Contact Lens","Fit scleral CL for irregular corneas and severe dry eye. Landing zone assessment, vault optimization, and fogging troubleshooting.",["scleral lens","scleral fitting","vault","landing zone","irregular cornea","PROSE","haptic"],"Scleral lens specialist."))
S.append(("orthokeratology","Contact Lens","Design ortho-K treatment for myopia control with reverse geometry lens design and topography-guided fitting.",["orthokeratology","ortho-K","myopia control","corneal reshaping","overnight lens","reverse geometry","Paragon CRT"],"Ortho-K specialist."))
S.append(("cosmetic-contact-lens","Contact Lens","Fit cosmetic and prosthetic CL including colored lenses, prosthetic iris for aniridia, and scleral shell prosthetics.",["cosmetic CL","colored lens","prosthetic lens","aniridia","scleral shell","prosthetic iris"],"Cosmetic/prosthetic CL agent."))
S.append(("contact-lens-materials-science","Contact Lens","Analyze CL material properties: Dk/t, water content, modulus, wettability, deposit resistance across HEMA, SiHy, and hydrogel.",["CL material","Dk","oxygen transmissibility","water content","modulus","HEMA","silicone hydrogel"],"Material science agent."))
S.append(("contact-lens-complications","Contact Lens","Diagnose CL complications: corneal infiltrates, neovascularization, GPC, CLARE, microbial keratitis, SLK.",["CL complication","corneal infiltrate","neovascularization","GPC","CLARE","microbial keratitis"],"CL complication diagnostician."))
S.append(("contact-lens-aftercare","Contact Lens","Comprehensive CL aftercare: lens assessment, fit evaluation, corneal health, compliance review, replacement schedule.",["CL aftercare","follow-up","lens check","compliance","replacement schedule"],"Aftercare monitoring agent."))
S.append(("multifocal-contact-lens","Contact Lens","Fit multifocal CL using concentric, aspheric, and translating designs with add adjustment and distance/near troubleshooting.",["multifocal CL","bifocal CL","presbyopia CL","near vision CL","concentric","aspheric CL"],"Multifocal CL specialist."))
S.append(("contact-lens-tear-film","Contact Lens","Evaluate tear film compatibility with CL wear: TBUT, Schirmer, osmolarity, meibography, and lipid layer analysis.",["tear film","TBUT","Schirmer","osmolarity","dry eye CL","meibography","lipid layer"],"Tear film compatibility agent."))
S.append(("contact-lens-solutions","Contact Lens","Recommend CL care systems: multipurpose, hydrogen peroxide, saline, daily disposables. Troubleshoot solution incompatibility.",["CL solution","multipurpose","hydrogen peroxide","CleanCare","saline","solution allergy"],"Solution advisor."))
S.append(("contact-lens-parameter-calculation","Contact Lens","Calculate CL parameters: sagittal depth, base curve from K, power compensation for vertex distance, toric rotation compensation.",["CL parameters","sagittal depth","base curve calculation","power compensation","toric calculation"],"CL mathematics agent."))
S.append(("myopia-control-cl","Contact Lens","Implement CL myopia control: MiSight dual-focus, multifocal soft CL off-label, ortho-K. Monitor axial length progression.",["myopia control CL","MiSight","dual focus","myopia management","axial length"],"Myopia control CL agent."))
S.append(("aphakic-contact-lens","Contact Lens","Fit CL for aphakic patients: pediatric silicone elastomer lenses, high-plus adult aphakic CL, and combination with spectacles.",["aphakic CL","pediatric aphakia","silicone elastomer","high plus CL","aphakia"],"Aphakic CL specialist."))
S.append(("contact-lens-compliance-counseling","Contact Lens","Structured compliance counseling for CL wearers: hygiene, replacement schedules, risk behaviors, and warning signs.",["CL compliance","hygiene","CL education","replacement schedule","sleeping in CL"],"Patient education agent."))
S.append(("hybrid-contact-lens","Contact Lens","Fit hybrid CL (soft skirt + RGP center) for keratoconus, post-surgical, and irregular cornea patients.",["hybrid CL","SynergEyes","soft skirt","RGP center","hybrid fitting"],"Hybrid CL specialist."))
S.append(("bandage-contact-lens","Contact Lens","Apply bandage CL for epithelial healing: post-PRK, recurrent erosions, filamentary keratitis, post-surgical protection.",["bandage CL","therapeutic CL","healing","post-PRK","recurrent erosion","epithelial protection"],"Therapeutic CL agent."))
S.append(("contact-lens-economics","Contact Lens","Analyze CL cost-effectiveness: daily vs monthly, insurance optimization, rebate programs, practice CL revenue modeling.",["CL cost","daily vs monthly","CL economics","rebate","insurance CL","practice revenue"],"CL economics agent."))
S.append(("contact-lens-regulations","Contact Lens","Navigate CL regulatory requirements: FDA classification, prescription verification laws, online retailer regulations.",["CL regulation","FDA","prescription verification","online CL","CL law","regulatory compliance"],"Regulatory compliance agent."))
S.append(("contact-lens-topography-integration","Contact Lens","Integrate corneal topography into CL fitting: Placido, Scheimpflug, OCT interpretation for RGP and scleral design.",["CL topography","corneal topography","Placido","Scheimpflug","Pentacam","topography fitting"],"Topography integration agent."))
S.append(("extended-wear-consultation","Contact Lens","Evaluate extended wear candidates. Assess risk factors, select high-Dk materials, establish monitoring protocols.",["extended wear","overnight CL","continuous wear","30-day CL","high Dk"],"Extended wear advisor."))
S.append(("contact-lens-troubleshooting","Contact Lens","Systematically troubleshoot CL complaints: poor vision, discomfort, dryness, movement issues, deposits, allergic reactions.",["CL problem","CL troubleshooting","poor vision CL","discomfort","deposits","CL allergy"],"CL problem-solver."))
S.append(("presbyopic-cl-strategy","Contact Lens","Develop presbyopic CL strategy: monovision, modified monovision, multifocal CL, distance CL + readers.",["monovision","modified monovision","presbyopia strategy","CL presbyopia","lifestyle matching"],"Presbyopic CL strategy agent."))
S.append(("contact-lens-digital-imaging","Contact Lens","Document CL fitting with slit-lamp photography, anterior OCT, and corneal topography for clinical records.",["CL imaging","slit-lamp photo","anterior OCT","CL documentation","telemedicine CL"],"Imaging documentation agent."))
S.append(("lens-wettability-assessment","Contact Lens","Assess CL wettability: tear breakup over lens, pre-lens tear film stability, deposition pattern analysis.",["wettability","pre-lens tear film","deposition","surface treatment","lens wetting"],"Wettability assessment agent."))
S.append(("contact-lens-inventory","Contact Lens","Manage CL trial lens inventory: diagnostic set organization, expiration tracking, parameter gap analysis.",["CL inventory","trial lens","diagnostic set","reorder","stock management"],"Inventory management agent."))
S.append(("prosthetic-lens-design","Contact Lens","Design prosthetic CL for disfigured eyes: hand-painted iris, black scleral lenses, cosmetic enhancement for coloboma.",["prosthetic design","hand-painted iris","black scleral","iris coloboma","photophobia lens"],"Prosthetic design agent."))
S.append(("contact-lens-enucleation","Contact Lens","Remove stuck/fused CL using suction cups, viscoelastic, and irrigation. Manage embedded lenses and retained fragments.",["stuck lens","removed CL","embedded lens","retained CL","suction cup","difficult removal"],"Emergency CL removal agent."))

# ── 3. BINOCULAR VISION (66-100) ──
S.append(("cover-test","Binocular Vision","Perform cover-uncover, alternate cover, and prism alternate cover to detect and measure heterotropias and heterophorias.",["cover test","alternate cover","heterotropia","heterophoria","strabismus","prism diopter"],"Strabismus detection agent."))
S.append(("vergence-assessment","Binocular Vision","Assess vergence amplitudes: blur, break, recovery for BI/BO at distance and near. Compare to Morgan norms.",["vergence","BO","BI","break point","recovery","Morgan norms","convergence","divergence"],"Vergence measurement agent."))
S.append(("stereopsis-testing","Binocular Vision","Measure stereopsis using Titmus, Randot, TNO, Frisby. Record threshold in seconds of arc.",["stereopsis","Titmus","Randot","TNO","Frisby","3D vision","stereoacuity","depth perception"],"Stereopsis assessment agent."))
S.append(("accommodative-facility","Binocular Vision","Measure accommodative facility using flipper lenses (+/-2.00D). Record cycles per minute, compare to norms.",["accommodative facility","flipper","lens flip","cpm","accommodative infacility"],"Facility testing agent."))
S.append(("npc-measurement","Binocular Vision","Measure NPC using push-up and penlight methods. Record break/recovery distances, identify convergence insufficiency.",["NPC","near point convergence","break point","convergence insufficiency","push-up convergence"],"NPC measurement agent."))
S.append(("fusional-reserves","Binocular Vision","Measure horizontal/vertical fusional reserves using prism bars. Apply Sheard and Percival criteria.",["fusional reserve","prism bar","horizontal fusion","vertical fusion","Sheard criterion","Percival criterion"],"Fusion reserve agent."))
S.append(("worth-4-dot-test","Binocular Vision","Worth 4 Dot at distance/near to assess suppression and fusion. Differentiate ARC patterns.",["Worth 4","Worth 4 dot","suppression","fusion","ARC","anomalous correspondence"],"Suppression detection agent."))
S.append(("bagolini-striated-lens","Binocular Vision","Bagolini striated lens test for sensory status in strabismus. Differentiate harmonious/unharmonious ARC.",["Bagolini","striated lens","ARC","sensory status","natural viewing","retinal correspondence"],"Sensory status agent."))
S.append(("4-base-out-test","Binocular Vision","4 Prism Diopter Base-Out test for microtropia and small-angle suppression detection.",["4 BO","4 base out","microtropia","small angle","suppression test","microstrabismus"],"Microtropia screening agent."))
S.append(("vertical-phoria-assessment","Binocular Vision","Assess vertical phorias using Maddox rod, double Maddox rod, and prism cover test.",["vertical phoria","Maddox rod","hyperphoria","hypophoria","cyclovertical","oblique dysfunction"],"Vertical deviation agent."))
S.append(("convergence-insufficiency-treatment","Binocular Vision","Design CI treatment: in-office vision therapy, home exercises (pencil push-ups, Brock string, stereograms), prism.",["convergence insufficiency treatment","vision therapy","pencil push-ups","Brock string","CI therapy"],"CI treatment planner."))
S.append(("amblyopia-management","Binocular Vision","Manage amblyopia: refractive correction, occlusion, penalization, atropine, binocular/dichoptic treatment.",["amblyopia","lazy eye","occlusion","patching","penalization","atropine amblyopia","dichoptic"],"Amblyopia management agent."))
S.append(("strabismus-classification","Binocular Vision","Classify strabismus: esotropia/exotropia/hypertropia, constant/intermittent, comitant/incomitant, congenital/acquired.",["strabismus","esotropia","exotropia","comitant","incomitant","congenital","acquired"],"Strabismus classifier."))
S.append(("accommodative-esotropia","Binocular Vision","Manage accommodative esotropia subtypes: fully/partially/non-accommodative. Bifocal Rx, miotic therapy, surgical referral.",["accommodative esotropia","refractive esotropia","bifocal esotropia","miotic","AC/A ratio"],"Accommodative esotropia specialist."))
S.append(("ac-a-ratio","Binocular Vision","Measure AC/A ratio using gradient and heterophoria methods. Guide bifocal add and surgical planning.",["AC/A ratio","gradient method","heterophoria method","convergence accommodation","high AC/A"],"AC/A assessment agent."))
S.append(("dissociated-vertical-deviation","Binocular Vision","Diagnose DVD in infantile esotropia. Measure amplitude and determine surgical referral criteria.",["DVD","dissociated vertical deviation","infantile esotropia","hyperdeviation","latent DVD"],"DVD diagnostician."))
S.append(("nystagmus-assessment","Binocular Vision","Assess nystagmus: congenital motor/sensory, acquired, jerk/pendular, null zone identification, compensatory strategies.",["nystagmus","null zone","jerk nystagmus","pendular","congenital nystagmus","head turn","Kestenbaum"],"Nystagmus assessment agent."))
S.append(("motor-alignment-surgery-comanagement","Binocular Vision","Co-manage strabismus surgery: pre-op measurements, surgical planning input, post-op alignment assessment, and reoperation criteria.",["strabismus surgery","surgical co-management","pre-op strabismus","post-op alignment","reoperation"],"Surgical co-management agent."))
S.append(("exotropia-management","Binocular Vision","Manage intermittent and constant exotropia: divergence excess, convergence insufficiency, basic type. Monitor control, prescribe minus lenses, and refer for surgery.",["exotropia","intermittent exotropia","divergence excess","XT surgery","lateral rectus"],"Exotropia management agent."))
S.append(("suppression-scanning","Binocular Vision","Detect and map suppression scotomas using Bagolini lenses, Worth 4 Dot, and vectographic techniques. Assess density and extent.",["suppression","suppression scotoma","suppression mapping","suppression density","ARC"],"Suppression mapping agent."))
S.append(("retinal-correspondence","Binocular Vision","Evaluate retinal correspondence: normal, harmonious ARC, unharmonious ARC using Bagolini, afterimage, and synoptophore.",["retinal correspondence","ARC","NRC","harmonious ARC","unharmonious ARC","afterimage test","synoptophore"],"Correspondence evaluation agent."))
S.append(("vision-therapy-exercises","Binocular Vision","Design and prescribe vision therapy exercise protocols: Brock string, stereograms, tranaglyphs, computerized VT, and home-based programs.",["vision therapy","VT exercises","Brock string","stereogram","tranaglyph","computerized VT","home therapy"],"VT exercise design agent."))
S.append(("prism-prescription","Binocular Vision","Calculate and prescribe prisms for horizontal and vertical deviations, compensatory prisms for nystagmus, and Fresnel prism application.",["prism","prism prescription","Fresnel prism","compensatory prism","prism diopter","yoked prism"],"Prism calculation agent."))
S.append(("sensory-fusion-assessment","Binocular Vision","Assess sensory fusion using Worth 4 Dot, synoptophore, and stereopsis tests. Determine fusion potential for surgical planning.",["sensory fusion","fusion potential","synoptophore","fusion assessment","binocular sensory"],"Sensory fusion evaluator."))
S.append(("convergence-excess","Binocular Vision","Diagnose convergence excess: high AC/A ratio, esophoria greater at near. Manage with bifocal adds, vision therapy, and surgical referral.",["convergence excess","high AC/A","near esophoria","bifocal add","CE therapy"],"Convergence excess management agent."))
S.append(("divergence-insufficiency","Binocular Vision","Diagnose divergence insufficiency: esophoria greater at distance. Manage with base-in prisms, vision therapy, and surgical referral criteria.",["divergence insufficiency","distance esophoria","BI prism","DI therapy","esophoria distance"],"Divergence insufficiency specialist."))
S.append(("tropia-vs-phoria","Binocular Vision","Differentiate tropia from phoria using cover-uncover test. Quantify deviation, assess control grading for intermittent deviations.",["tropia","phoria","manifest","latent","control grading","cover-uncover","deviation type"],"Deviation classification agent."))
S.append(("motor-fusion","Binocular Vision","Evaluate motor fusion capacity using prism bars and rotary prisms at distance and near. Determine fusional vergence amplitudes and recruitment patterns.",["motor fusion","fusional vergence","prism bar","vergence amplitudes","fusion capacity"],"Motor fusion assessment agent."))
S.append(("diplopia-assessment","Binocular Vision","Assess diplopia: monocular vs binocular, horizontal/vertical/torsional, constant/intermittent. Localize cranial nerve palsy and myasthenia.",["diplopia","double vision","cranial nerve","myasthenia","torsional diplopia","binocular diplopia"],"Diplopia diagnostician."))
S.append(("cranial-nerve-palsy","Binocular Vision","Evaluate cranial nerve III, IV, VI palsies: deviation patterns, forced duction test interpretation, neuroimaging referral, and management timeline.",["CN III","CN IV","CN VI","cranial nerve palsy","nerve palsy","third nerve","fourth nerve","sixth nerve"],"Cranial nerve palsy agent."))
S.append(("bell-palsy-ocular","Binocular Vision","Manage ocular complications of Bell palsy: exposure keratopathy, lagophthalmos, dry eye management, and protective measures.",["Bell palsy","lagophthalmos","exposure keratopathy","facial nerve","ocular Bell palsy"],"Bell palsy ocular management agent."))
S.append(("thyroid-eye-disease-bv","Binocular Vision","Assess binocular vision changes in thyroid eye disease: restrictive myopathy, measurement of的限制性斜视, and surgical timing.",["thyroid eye disease","TED","Graves ophthalmopathy","restrictive strabismus","thyroid myopathy","double vision TED"],"TED binocular vision agent."))
S.append(("head-tilt-assessment","Binocular Vision","Evaluate abnormal head posture: head tilt, face turn, chin elevation/depression. Differentiate ocular vs cervical causes using cover test in positions.",["head tilt","head posture","face turn","chin position","abnormal head posture","torticollis"],"Head posture evaluation agent."))
S.append(("ocular-motility-exam","Binocular Vision","Perform comprehensive 9-position ocular motility examination. Identify underaction and overaction of extraocular muscles.",["ocular motility","motility exam","9 positions","Ductions","versions","overaction","underaction"],"Motility examination agent."))
S.append(("monocular-elevation-deficiency","Binocular Vision","Diagnose monocular elevation deficiency (double elevator palsy). Differentiate from inferior orbital blowout and myasthenia.",["monocular elevation deficiency","double elevator","inferior rectus","blowout fracture","upgaze palsy"],"Elevation deficiency diagnostician."))
S.append(("brown-syndrome","Binocular Vision","Diagnose Brown syndrome (superior oblique tendon sheath syndrome). Assess click syndrome, congenital vs acquired, and management.",["Brown syndrome","superior oblique","click syndrome","elevation limitation","congenital Brown"],"Brown syndrome diagnostician."))

# ── 4. OCULAR ANATOMY & PHYSIOLOGY (101-120) ──
S.append(("corneal-anatomy","Ocular Anatomy","Detailed corneal anatomy: 5 layers (epithelium, Bowman, stroma, Descemet, endothelium), innervation, metabolism, and wound healing.",["corneal anatomy","corneal layers","epithelium","Bowman layer","Descemet","endothelium","corneal wound healing"],"Corneal anatomy expert."))
S.append(("retinal-anatomy","Ocular Anatomy","Retinal anatomy: 10 layers, macula, fovea, optic disc, vasculature. Histology and function of photoreceptors, bipolar, ganglion cells.",["retinal anatomy","retinal layers","macula","fovea","optic disc","photoreceptors","rods","cones"],"Retinal anatomy expert."))
S.append(("lens-anatomy","Ocular Anatomy","Crystalline lens anatomy: capsule, epithelium, cortex, nucleus. Accommodation mechanism, ciliary body interaction, and age-related changes.",["lens anatomy","crystalline lens","capsule","nucleus","cortex","accommodation mechanism","cataract formation"],"Lens anatomy expert."))
S.append(("vitreous-anatomy","Ocular Anatomy","Vitreous anatomy: composition, gel structure, vitreous base, Cloquet canal, and age-related liquefaction (syneresis) and posterior vitreous detachment.",["vitreous","vitreous gel","vitreous base","Cloquet canal","syneresis","PVD","vitreous detachment"],"Vitreous anatomy expert."))
S.append(("optic-nerve-anatomy","Ocular Anatomy","Optic nerve anatomy: 4 segments (intraocular, intraorbital, intracanalicular, intracranial), retinal ganglion cell axons, blood supply, and CSF pressure relationship.",["optic nerve","optic disc","retinal ganglion","intraorbital","intracranial","CSF pressure","optic nerve head"],"Optic nerve anatomy expert."))
S.append(("extraocular-muscles","Ocular Anatomy","Six extraocular muscles: origin, insertion, innervation, primary/secondary/tertiary actions. Action tables and clinical testing correlations.",["extraocular muscles","lateral rectus","medial rectus","superior rectus","inferior rectus","superior oblique","inferior oblique","CN supply"],"EOM anatomy expert."))
S.append(("ocular-circulation","Ocular Anatomy","Ocular blood supply: ophthalmic artery branches, retinal circulation (central retinal artery), choroidal circulation, and venous drainage.",["ophthalmic artery","central retinal artery","choroidal circulation","ophthalmic vein","ciliary arteries","circle of Zinn"],"Ocular circulation expert."))
S.append(("visual-pathway","Ocular Anatomy","Visual pathway from retina to occipital cortex: optic nerve, chiasm, tract, LGN, optic radiations, visual cortex. Lesion localization.",["visual pathway","optic chiasm","optic tract","LGN","optic radiations","visual cortex","lesion localization"],"Visual pathway expert."))
S.append(("tear-film-physiology","Ocular Anatomy","Tear film: 3 layers (lipid, aqueous, mucin), glands (meibomian, lacrimal, goblet cells), turnover rate, and stability factors.",["tear film","lipid layer","aqueous layer","mucin","meibomian gland","lacrimal gland","tear physiology"],"Tear film physiology expert."))
S.append(("pupil-physiology","Ocular Anatomy","Pupil physiology: sphincter and dilator muscles, parasympathetic/sympathetic innervation, light reflex pathway, near reflex, and pharmacological effects.",["pupil","pupil reflex","light reflex","near reflex","parasympathetic","sympathetic","Adie","Argyll Robertson"],"Pupil physiology expert."))
S.append(("aqueous-humour-dynamics","Ocular Anatomy","Aqueous humor: production (ciliary body), outflow (trabecular, uveoscleral), intraocular pressure relationship, and pharmacological modification.",["aqueous humor","IOP","trabecular meshwork","Schlemm canal","uveoscleral outflow","ciliary body","aqueous production"],"Aqueous dynamics expert."))
S.append(("eyelid-anatomy","Ocular Anatomy","Eyelid anatomy: layers, tarsal plates, glands, muscles (orbicularis, levator, Mueller), sensory innervation, and blink mechanism.",["eyelid","tarsal plate","meibomian gland","orbicularis","levator","Mueller muscle","blink mechanism"],"Eyelid anatomy expert."))
S.append(("conjunctival-anatomy","Ocular Anatomy","Conjunctival anatomy: palpebral, bulbar, fornix, fornices. Goblet cells, lymphoid tissue (CALT), and clinical significance.",["conjunctiva","palpebral","bulbar","fornix","goblet cells","CALT","conjunctival anatomy"],"Conjunctival anatomy expert."))
S.append(("scleral-anatomy","Ocular Anatomy","Scleral anatomy: collagen lamellae, thickness variation, emissary canals, scleral spur, and relationship to extraocular muscle insertions.",["sclera","scleral anatomy","collagen","scleral spur","emissary canals","lamina cribrosa"],"Scleral anatomy expert."))
S.append(("uvea-anatomy","Ocular Anatomy","Uveal tract: iris, ciliary body, choroid. Histology, blood supply, and clinical correlations with uveitis and tumors.",["uvea","iris","ciliary body","choroid","uveal tract","uveitis","uveal melanoma"],"Uveal anatomy expert."))
S.append(("foveal-microanatomy","Ocular Anatomy","Foveal microanatomy: foveola, fovea, parafovea, perifovea. Cone density, avascular zone, and relationship to visual acuity.",["fovea","foveola","parafovea","cone density","avascular zone","foveal anatomy"],"Foveal specialist."))
S.append(("ocular-embryology","Ocular Anatomy","Ocular embryology: lens vesicle, optic cup, choroidal fissure, hyaloid vasculature, and congenital anomalies from developmental arrest.",["ocular embryology","lens vesicle","optic cup","choroidal fissure","hyaloid","congenital anomaly","developmental"],"Embryology expert."))
S.append(("lacrimal-system-anatomy","Ocular Anatomy","Lacrimal drainage system: puncta, canaliculi, lacrimal sac, nasolacrimal duct. Anatomy of nasolacrimal obstruction and DCR surgery.",["lacrimal system","lacrimal drainage","punctum","canaliculus","lacrimal sac","nasolacrimal duct","DCR"],"Lacrimal system expert."))
S.append(("ocular-immunology","Ocular Anatomy","Ocular immunology: immune privilege, anterior chamber-associated immune deviation (ACAID), mucosal immunity, and ocular surface immune defense.",["ocular immunology","immune privilege","ACAID","ocular surface immunity","mucosal immunity","immune response eye"],"Ocular immunology expert."))
S.append(("neuro-ophthalmic-anatomy","Ocular Anatomy","Neuro-ophthalmic anatomy: brainstem nuclei, cranial nerve pathways, cortical visual areas, and supranuclear gaze centers.",["neuro-ophthalmic","brainstem","cranial nerve nuclei","supranuclear gaze","cortical visual","neuro anatomy"],"Neuro-ophthalmic anatomy expert."))

# ── 5. OCULAR DISEASE - ANTERIOR SEGMENT (121-160) ──
S.append(("conjunctivitis-diagnosis","Anterior Segment Disease","Diagnose conjunctivitis types: viral, bacterial, allergic, chlamydial. Differentiate by signs, symptoms, and diagnostic tests.",["conjunctivitis","pink eye","viral conjunctivitis","bacterial conjunctivitis","allergic conjunctivitis","chlamydia eye"],"Conjunctivitis diagnostician."))
S.append(("keratitis-diagnosis","Anterior Segment Disease","Diagnose keratitis: infectious (bacterial, viral HSV, fungal, Acanthamoeba) vs non-infectious. Workup includes cultures, staining, and confocal microscopy.",["keratitis","corneal ulcer","bacterial keratitis","HSV keratitis","fungal keratitis","Acanthamoeba","corneal infection"],"Keratitis diagnostician."))
S.append(("dry-eye-evaluation","Anterior Segment Disease","Comprehensive dry eye evaluation: TBUT, Schirmer, osmolarity, meibography, staining (fluorescein, lissamine, rose bengal), and DEWS classification.",["dry eye","dry eye syndrome","TBUT","Schirmer","osmolarity","meibography","DEWS","MGD"],"Dry eye specialist."))
S.append(("cataract-classification","Anterior Segment Disease","Classify cataracts: nuclear, cortical, posterior subcapsular, congenital, traumatic, and drug-induced. Grade using LOCS III and determine surgical timing.",["cataract","nuclear sclerosis","cortical cataract","PSC","LOCS III","cataract grading","cataract surgery timing"],"Cataract classification agent."))
S.append(("glaucoma-screening","Anterior Segment Disease","Screen for glaucoma: IOP measurement, optic disc assessment (CDR, rim thinning, notching), visual fields, and OCT RNFL/GCC analysis.",["glaucoma","IOP","intraocular pressure","optic disc","CDR","visual field","OCT RNFL","cupping"],"Glaucoma screening agent."))
S.append(("pterygium-assessment","Anterior Segment Disease","Assess pterygium: grade (1-3), extent of corneal involvement, visual impact, and surgical referral criteria. Manage postoperative recurrence prevention.",["pterygium","pinguecula","pterygium surgery","corneal extension","pterygium grade","recurrence"],"Pterygium assessment agent."))
S.append(("corneal-dystrophy","Anterior Segment Disease","Diagnose corneal dystrophies: Fuchs endothelial, lattice, granular, macular, epithelial basement membrane, and Meesmann. Use specular microscopy and confocal.",["corneal dystrophy","Fuchs","lattice dystrophy","granular dystrophy","EBMD","Meesmann","endothelial dystrophy"],"Corneal dystrophy specialist."))
S.append(("uveitis-ant